name: build
on:
    push:
        branches: [ '*' ]
    pull_request:
        branches: [ '*' ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: '8'
            -   name: maven build
                run: mvn --batch-mode --errors --show-version --no-transfer-progress clean verify
